version: '3'

services:
  db:
    container_name: db
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mysql-db
        target: /var/lib/mysql

  api:
    container_name: api
    tty: true
    depends_on:
      - db
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./back
        target: /pdapi
    env_file:
      - ./back/.env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  app:
    container_name: app
    build:
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./front
        target: /frontapp
    env_file:
      - ./front/.env
    command: yarn dev

volumes:
  mysql-db:
